/**
 * Orchestration Calendar Mock Data
 *
 * 18 items covering all 3 pillars, all 6 statuses, all 3 modes, mixed risk levels.
 * Dates centered around 2026-02-20 (stable reference to avoid hydration mismatch).
 *
 * @see /docs/canon/ORCHESTRATION_CALENDAR_CONTRACT.md §4
 */

import type { CalendarItem } from '../command-center/types';

export const MOCK_CALENDAR_ITEMS: CalendarItem[] = [
  // ── PR PILLAR ──────────────────────────────────────
  {
    id: 'cal-01',
    date: '2026-02-18',
    time: '09:00',
    pillar: 'pr',
    title: 'TechCrunch follow-up email',
    status: 'published',
    mode: 'copilot',
    details: {
      summary: 'Copilot drafted personalized follow-up to TechCrunch reporter after product demo. Sent on schedule.',
      owner: 'AI',
      risk: 'med',
      estimated_duration: '5 min',
      dependencies: [],
    },
    linked: { action_id: 'act-12', campaign_id: 'camp-01' },
  },
  {
    id: 'cal-02',
    date: '2026-02-19',
    time: '10:30',
    pillar: 'pr',
    title: 'Press release: Q1 product launch',
    status: 'awaiting_approval',
    mode: 'copilot',
    details: {
      summary: 'SAGE-generated press release for Q1 product launch. Requires human review before distribution.',
      owner: 'AI',
      risk: 'high',
      estimated_duration: '15 min review',
      dependencies: ['Legal team sign-off'],
    },
    linked: { action_id: 'act-15', campaign_id: 'camp-01' },
  },
  {
    id: 'cal-03',
    date: '2026-02-20',
    time: '08:00',
    pillar: 'pr',
    title: 'Journalist relationship scoring update',
    status: 'scheduled',
    mode: 'autopilot',
    details: {
      summary: 'Automated re-scoring of journalist relationship strength based on recent interactions.',
      owner: 'AI',
      risk: 'low',
      estimated_duration: '3 min',
      dependencies: [],
    },
    linked: { action_id: null, campaign_id: null },
  },
  {
    id: 'cal-04',
    date: '2026-02-20',
    time: '14:00',
    pillar: 'pr',
    title: 'Analyst briefing prep deck',
    status: 'drafting',
    mode: 'copilot',
    details: {
      summary: 'SAGE is generating a briefing deck for the upcoming analyst call. Entity coverage data being pulled.',
      owner: 'AI',
      risk: 'high',
      estimated_duration: '20 min',
      dependencies: ['Q1 revenue data'],
    },
    linked: { action_id: 'act-18', campaign_id: 'camp-02' },
  },
  {
    id: 'cal-05',
    date: '2026-02-21',
    time: '11:00',
    pillar: 'pr',
    title: 'Media monitoring report',
    status: 'planned',
    mode: 'autopilot',
    details: {
      summary: 'Weekly media monitoring digest covering brand mentions and competitor activity.',
      owner: 'AI',
      risk: 'low',
      estimated_duration: '2 min',
      dependencies: [],
    },
    linked: { action_id: null, campaign_id: null },
  },
  {
    id: 'cal-06',
    date: '2026-02-19',
    time: '16:00',
    pillar: 'pr',
    title: 'Outreach to Wired editor',
    status: 'failed',
    mode: 'autopilot',
    details: {
      summary: 'Automated outreach email failed — recipient bounce detected. Email address may be outdated.',
      owner: 'AI',
      risk: 'med',
      estimated_duration: '1 min',
      dependencies: [],
    },
    linked: { action_id: 'act-20', campaign_id: 'camp-01' },
  },

  // ── CONTENT PILLAR ─────────────────────────────────
  {
    id: 'cal-07',
    date: '2026-02-18',
    time: '14:00',
    pillar: 'content',
    title: 'Marketing Automation Guide — publish',
    status: 'published',
    mode: 'manual',
    details: {
      summary: 'Manual publish of the Ultimate Guide to Marketing Automation. CiteMind AEO score 82.',
      owner: 'User',
      risk: 'med',
      estimated_duration: '5 min',
      dependencies: [],
    },
    linked: { action_id: 'act-08', campaign_id: 'camp-03' },
  },
  {
    id: 'cal-08',
    date: '2026-02-20',
    time: '10:00',
    pillar: 'content',
    title: 'Content Strategy 2026 article — draft',
    status: 'drafting',
    mode: 'copilot',
    details: {
      summary: 'Copilot generating first draft based on SAGE content brief. Targeting AEO score 70+.',
      owner: 'AI',
      risk: 'low',
      estimated_duration: '30 min',
      dependencies: ['Keyword research complete'],
    },
    linked: { action_id: 'act-22', campaign_id: 'camp-03' },
  },
  {
    id: 'cal-09',
    date: '2026-02-20',
    time: '15:00',
    pillar: 'content',
    title: 'Lead gen case study — review',
    status: 'awaiting_approval',
    mode: 'copilot',
    details: {
      summary: 'AI-drafted case study ready for editorial review. AEO score preview: 71. Schema markup included.',
      owner: 'AI',
      risk: 'med',
      estimated_duration: '10 min review',
      dependencies: ['Client approval of quotes'],
    },
    linked: { action_id: 'act-23', campaign_id: 'camp-03' },
  },
  {
    id: 'cal-10',
    date: '2026-02-21',
    time: '09:00',
    pillar: 'content',
    title: 'Social media derivative posts',
    status: 'planned',
    mode: 'autopilot',
    details: {
      summary: 'Generate 5 social posts from the Marketing Automation Guide. Auto-publish to LinkedIn.',
      owner: 'AI',
      risk: 'low',
      estimated_duration: '10 min',
      dependencies: ['Marketing Automation Guide published'],
    },
    linked: { action_id: null, campaign_id: 'camp-03' },
  },
  {
    id: 'cal-11',
    date: '2026-02-22',
    time: '13:00',
    pillar: 'content',
    title: 'Email newsletter — send',
    status: 'scheduled',
    mode: 'manual',
    details: {
      summary: 'Weekly newsletter featuring top content. Manually scheduled for Thursday 1pm send.',
      owner: 'User',
      risk: 'med',
      estimated_duration: '2 min',
      dependencies: [],
    },
    linked: { action_id: 'act-25', campaign_id: null },
  },
  {
    id: 'cal-12',
    date: '2026-02-17',
    time: '11:00',
    pillar: 'content',
    title: 'Blog post schema deployment',
    status: 'failed',
    mode: 'autopilot',
    details: {
      summary: 'Attempted to deploy NewsArticle schema to 3 blog posts. CMS API returned 429 rate limit.',
      owner: 'AI',
      risk: 'low',
      estimated_duration: '1 min',
      dependencies: [],
    },
    linked: { action_id: 'act-27', campaign_id: null },
  },

  // ── SEO PILLAR ─────────────────────────────────────
  {
    id: 'cal-13',
    date: '2026-02-19',
    time: '07:00',
    pillar: 'seo',
    title: 'Organization schema deployment',
    status: 'published',
    mode: 'autopilot',
    details: {
      summary: 'Deployed Organization JSON-LD to homepage and 11 landing pages. AEO impact: +8 pts.',
      owner: 'AI',
      risk: 'low',
      estimated_duration: '5 min',
      dependencies: [],
    },
    linked: { action_id: 'act-30', campaign_id: null },
  },
  {
    id: 'cal-14',
    date: '2026-02-20',
    time: '06:00',
    pillar: 'seo',
    title: 'Citation scan — daily',
    status: 'scheduled',
    mode: 'autopilot',
    details: {
      summary: 'Automated daily scan for new AI citations across ChatGPT, Perplexity, and Gemini.',
      owner: 'AI',
      risk: 'low',
      estimated_duration: '8 min',
      dependencies: [],
    },
    linked: { action_id: null, campaign_id: null },
  },
  {
    id: 'cal-15',
    date: '2026-02-20',
    time: '11:00',
    pillar: 'seo',
    title: 'FAQ schema repair — 3 pages',
    status: 'awaiting_approval',
    mode: 'copilot',
    details: {
      summary: 'SAGE proposes repairing incomplete FAQ schema on 3 support pages. Estimated AEO impact: +5 pts.',
      owner: 'AI',
      risk: 'low',
      estimated_duration: '3 min',
      dependencies: [],
    },
    linked: { action_id: 'act-32', campaign_id: null },
  },
  {
    id: 'cal-16',
    date: '2026-02-21',
    time: '16:00',
    pillar: 'seo',
    title: 'Core Web Vitals optimization',
    status: 'planned',
    mode: 'manual',
    details: {
      summary: 'Manual performance optimization for 8 landing pages with LCP > 4s. DevOps coordination required.',
      owner: 'User',
      risk: 'med',
      estimated_duration: '2 hours',
      dependencies: ['DevOps availability'],
    },
    linked: { action_id: 'act-34', campaign_id: null },
  },
  {
    id: 'cal-17',
    date: '2026-02-22',
    time: '09:00',
    pillar: 'seo',
    title: 'IndexNow ping — updated pages',
    status: 'scheduled',
    mode: 'autopilot',
    details: {
      summary: 'Send IndexNow pings for 5 recently updated blog posts to accelerate re-indexing.',
      owner: 'AI',
      risk: 'low',
      estimated_duration: '1 min',
      dependencies: ['Blog posts updated'],
    },
    linked: { action_id: null, campaign_id: null },
  },
  {
    id: 'cal-18',
    date: '2026-02-20',
    time: '17:00',
    pillar: 'seo',
    title: 'Meta description deduplication',
    status: 'drafting',
    mode: 'copilot',
    details: {
      summary: 'Generating unique meta descriptions for 7 blog posts with duplicate metadata. Entity-rich copy.',
      owner: 'AI',
      risk: 'low',
      estimated_duration: '15 min',
      dependencies: [],
    },
    linked: { action_id: 'act-36', campaign_id: null },
  },
];
