/**
 * PDF Export Utility — client-side PDF generation via html2canvas + jsPDF
 *
 * Static imports so webpack bundles these into the client chunk.
 * This file should only be imported from 'use client' components.
 */

import jsPDF from 'jspdf';
import html2canvas from 'html2canvas';

const A4_WIDTH_MM = 210;
const A4_HEIGHT_MM = 297;
const MARGIN_MM = 12;
const CONTENT_WIDTH_MM = A4_WIDTH_MM - MARGIN_MM * 2;

/**
 * Capture a DOM element and generate a multi-page PDF.
 * The element should be rendered off-screen with light-theme styling.
 */
export async function generatePdf(element: HTMLElement, filename: string): Promise<void> {
  console.log('[PDF] Starting generation...');

  // Capture the element at 2x resolution for sharpness
  const canvas = await html2canvas(element, {
    scale: 2,
    useCORS: true,
    backgroundColor: '#ffffff',
    logging: false,
  });

  console.log('[PDF] Canvas captured:', canvas.width, 'x', canvas.height);

  const imgWidthPx = canvas.width;
  const imgHeightPx = canvas.height;

  // Calculate how the image maps to A4 pages
  const pxPerMm = imgWidthPx / CONTENT_WIDTH_MM;
  const contentHeightMm = imgHeightPx / pxPerMm;
  const pageContentHeightMm = A4_HEIGHT_MM - MARGIN_MM * 2;

  const pdf = new jsPDF('p', 'mm', 'a4');
  let yOffsetMm = 0;
  let page = 0;

  while (yOffsetMm < contentHeightMm) {
    if (page > 0) pdf.addPage();

    const remainingMm = contentHeightMm - yOffsetMm;
    const thisPageHeightMm = Math.min(pageContentHeightMm, remainingMm);

    // Source coordinates in pixel space
    const srcY = yOffsetMm * pxPerMm;
    const srcHeight = thisPageHeightMm * pxPerMm;

    // Create a cropped canvas for this page slice
    const pageCanvas = document.createElement('canvas');
    pageCanvas.width = imgWidthPx;
    pageCanvas.height = Math.ceil(srcHeight);
    const ctx = pageCanvas.getContext('2d')!;
    ctx.drawImage(canvas, 0, srcY, imgWidthPx, srcHeight, 0, 0, imgWidthPx, srcHeight);

    const pageImgData = pageCanvas.toDataURL('image/png');
    pdf.addImage(pageImgData, 'PNG', MARGIN_MM, MARGIN_MM, CONTENT_WIDTH_MM, thisPageHeightMm);

    // Footer
    pdf.setFontSize(8);
    pdf.setTextColor(150, 150, 150);
    pdf.text('Generated by Pravado · pravado.io · Confidential', A4_WIDTH_MM / 2, A4_HEIGHT_MM - 6, { align: 'center' });
    pdf.text(`Page ${page + 1}`, A4_WIDTH_MM - MARGIN_MM, A4_HEIGHT_MM - 6, { align: 'right' });

    yOffsetMm += pageContentHeightMm;
    page++;
  }

  console.log('[PDF] Saving:', filename);
  pdf.save(filename);
}
